version: 0.2

env:
  parameter-store:
    SONAR_LOGIN: "SONAR_LOGIN"
    AMAZON_AWS_ACCESSKEY: "AMAZON_AWS_ACCESSKEY"
    AMAZON_AWS_SECRETKEY: "AMAZON_AWS_SECRETKEY"

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn install -Damazon.dynamodb.endpoint=http://dynamodb.eu-central-1.amazonaws.com
      - git init
      - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN
  post_build:
    commands:
      # cleanup source artifact bucket
      - aws s3 rm --recursive "s3://codepipeline-eu-central-1-623791722169/grocery-tracker-back/SourceArti"
      # move built jar one folder level up to make it easier to package both the jar and the .ebextensions folder into one single zip
      - cd target
      - find . -name '*.jar' -exec mv {} .. \;
artifacts:
  files:
    - ./*.jar
    - .ebextensions/**/*