version: 0.2

env:
  parameter-store:
    SONAR_LOGIN: "SONAR_LOGIN"

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Login for sonarcloud $SONAR_LOGIN
      - mvn verify sonar:sonar -Dsonar.login=$SONAR_LOGIN
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mvn package
      - aws s3 rm --recursive "s3://codepipeline-eu-central-1-623791722169/grocery-tracker-back/SourceArti"
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  name: grocery-tracker-back-$AWS_REGION